name: Build site using PHP

on:
  workflow_dispatch:
  # * is a special character in YAML so you have to quote this string
  # scheduled every day at midnight
  # schedule:
    # - cron:  "0 0 * * *"

permissions:
  contents: write
  
# see https://jmh.me/blog/build-deploy-php-application-with-github-actions
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_DEV: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Checkout index.php
#        uses: actions/checkout@v4
#        with:
#          repository: robindotis/cwcms
#          path: cwcms
        
#      - run: cp ./cwcms/index.php index.php
#      - run: cp ./cwcms/composer.json composer.json
#      - run: rm -rf cwcms/
#      - run: ls -a
#      - run: echo "${{github.actor}}"
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer packages
        uses: ramsey/composer-install@v3

      - run: php ./index.php
#      - run: rm -rf vendor/

#      - name: Commit report
#        run: |
#          git config --global user.name 'robindotis'
#          git config --global user.email 'robindotis@users.noreply.github.com'
#          git add -A _site/*
#          git commit -m "Pushed from GitHub Actions"
#          git push
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
#        if: github.ref == 'refs/heads/main'
        with:
            personal_token: ${{ secrets.PERSONAL_TOKEN }}
            publish_dir: _site 
            publish_branch: main
            external_repository: robindotis/diyblog.github.io
#            github_token: ${{ secrets.GITHUB_TOKEN }}
#            publish_dir: ./_site 
